name: botswana-snap
version: 0.0.1
summary: Run any bot on any chat, painlessly!
description: Coming soon...

grade: devel
confinement: devmode

apps:
    deploy:
        command: env PATH=$PATH:$SNAP/libexec/git-core LC_ALL=C deploy_bot
parts:
    git:
        source: https://github.com/git/git
        source-type: git
        source-depth: 1
        plugin: autotools
        configflags:
            - --with-curl
            - --with-expat
        build-packages:
            - gettext
            - libssl-dev
            - libcurl4-openssl-dev
            - libexpat1-dev
        stage-packages:
            - libcurl3
    node:
        plugin: nodejs
        node-engine: 6.9.4
        node-packages:
            - yo
            - generator-hubot
        stage:
            - bin
            - lib/node_modules
        prime:
            - bin
            - lib/node_modules
    scripts:
        plugin: dump
        source: bin/
        organize:
            deploy_bot: bin/deploy_bot
        prime:
            - bin
